### ISSUE TITLE
Upgrade to PyTorch 2.0.1 and Torchvision 0.15.2

### ISSUE THREAD

**Issue by hongbo-miao** [hongbo-miao/hongbomiao.com#9510]
Waiting

- https://github.com/pytorch/pytorch/issues/100974

**Comment by ishan-modi** [comment]
please fix this facing the same issue

**Comment by hongbo-miao** [comment]
@ishan-modi You posted at wrong repo I think

**Comment by ishan-modi** [comment]
> @ishan-modi You posted at wrong repo I think

Ohh !
did that already. thanks for the reply though.

**Comment by hongbo-miao** [comment]
@ishan-modi Ha no problem! ☺️

**Comment by hongbo-miao** [comment]
Succeed to upgrade. The issue seems fixed.

- torch = "2.1.1"
- torchvision = "0.16.1"
